library(rospca)

test_df <- read.csv("/home/thiago/dev/anomaly-detection/network-attack-detection/data/ctu_13/csv_sum_test/datactu_13pkl_sum015s_10pk1_test_df.csv", header=TRUE, sep=",")
resRS <- robpca(test_df, k=10, skew=TRUE,ndir=5000)
write(resRS$flag.all, file = "robpca_k19_datactu_13pkl_sum015s_10pk1_test_df", sep = "\n")
test_df <- read.csv("/home/thiago/dev/anomaly-detection/network-attack-detection/data/ctu_13/csv_sum_test/datactu_13pkl_sum025s_10pk1_test_df.csv", header=TRUE, sep=",")
resRS <- robpca(test_df, k=10, skew=TRUE,ndir=5000)
write(resRS$flag.all, file = "robpca_k19_datactu_13pkl_sum025s_10pk1_test_df", sep = "\n")

test_df <- read.csv("/home/thiago/dev/anomaly-detection/network-attack-detection/data/ctu_13/csv_sum_test/datactu_13pkl_sum015s_11pk1_test_df.csv", header=TRUE, sep=",")
resRS <- robpca(test_df, k=10, skew=TRUE,ndir=5000)
write(resRS$flag.all, file = "robpca_k19_datactu_13pkl_sum015s_11pk1_test_df", sep = "\n")
test_df <- read.csv("/home/thiago/dev/anomaly-detection/network-attack-detection/data/ctu_13/csv_sum_test/datactu_13pkl_sum025s_11pk1_test_df.csv", header=TRUE, sep=",")
resRS <- robpca(test_df, k=10, skew=TRUE,ndir=5000)
write(resRS$flag.all, file = "robpca_k19_datactu_13pkl_sum025s_11pk1_test_df", sep = "\n")

test_df <- read.csv("/home/thiago/dev/anomaly-detection/network-attack-detection/data/ctu_13/csv_sum_test/datactu_13pkl_sum015s_12pk1_test_df.csv", header=TRUE, sep=",")
resRS <- robpca(test_df, k=10, skew=TRUE,ndir=5000)
write(resRS$flag.all, file = "robpca_k19_datactu_13pkl_sum015s_12pk1_test_df", sep = "\n")
test_df <- read.csv("/home/thiago/dev/anomaly-detection/network-attack-detection/data/ctu_13/csv_sum_test/datactu_13pkl_sum025s_12pk1_test_df.csv", header=TRUE, sep=",")
resRS <- robpca(test_df, k=10, skew=TRUE,ndir=5000)
write(resRS$flag.all, file = "robpca_k19_datactu_13pkl_sum025s_12pk1_test_df", sep = "\n")

test_df <- read.csv("/home/thiago/dev/anomaly-detection/network-attack-detection/data/ctu_13/csv_sum_test/datactu_13pkl_sum015s_15-2pk1_test_df.csv", header=TRUE, sep=",")
resRS <- robpca(test_df, k=10, skew=TRUE,ndir=5000)
write(resRS$flag.all, file = "robpca_k19_datactu_13pkl_sum015s_15-2pk1_test_df", sep = "\n")
test_df <- read.csv("/home/thiago/dev/anomaly-detection/network-attack-detection/data/ctu_13/csv_sum_test/datactu_13pkl_sum025s_15-2pk1_test_df.csv", header=TRUE, sep=",")
resRS <- robpca(test_df, k=10, skew=TRUE,ndir=5000)
write(resRS$flag.all, file = "robpca_k19_datactu_13pkl_sum025s_15-2pk1_test_df", sep = "\n")

test_df <- read.csv("/home/thiago/dev/anomaly-detection/network-attack-detection/data/ctu_13/csv_sum_test/datactu_13pkl_sum015s_15-3pk1_test_df.csv", header=TRUE, sep=",")
resRS <- robpca(test_df, k=10, skew=TRUE,ndir=5000)
write(resRS$flag.all, file = "robpca_k19_datactu_13pkl_sum015s_15-3pk1_test_df", sep = "\n")
test_df <- read.csv("/home/thiago/dev/anomaly-detection/network-attack-detection/data/ctu_13/csv_sum_test/datactu_13pkl_sum025s_15-3pk1_test_df.csv", header=TRUE, sep=",")
resRS <- robpca(test_df, k=10, skew=TRUE,ndir=5000)
write(resRS$flag.all, file = "robpca_k19_datactu_13pkl_sum025s_15-3pk1_test_df", sep = "\n")

test_df <- read.csv("/home/thiago/dev/anomaly-detection/network-attack-detection/data/ctu_13/csv_sum_test/datactu_13pkl_sum015s_15pk1_test_df.csv", header=TRUE, sep=",")
resRS <- robpca(test_df, k=10, skew=TRUE,ndir=5000)
write(resRS$flag.all, file = "robpca_k19_datactu_13pkl_sum015s_15pk1_test_df", sep = "\n")
test_df <- read.csv("/home/thiago/dev/anomaly-detection/network-attack-detection/data/ctu_13/csv_sum_test/datactu_13pkl_sum025s_15pk1_test_df.csv", header=TRUE, sep=",")
resRS <- robpca(test_df, k=10, skew=TRUE,ndir=5000)
write(resRS$flag.all, file = "robpca_k19_datactu_13pkl_sum025s_15pk1_test_df", sep = "\n")

test_df <- read.csv("/home/thiago/dev/anomaly-detection/network-attack-detection/data/ctu_13/csv_sum_test/datactu_13pkl_sum015s_16-2pk1_test_df.csv", header=TRUE, sep=",")
resRS <- robpca(test_df, k=10, skew=TRUE,ndir=5000)
write(resRS$flag.all, file = "robpca_k19_datactu_13pkl_sum015s_16-2pk1_test_df", sep = "\n")
test_df <- read.csv("/home/thiago/dev/anomaly-detection/network-attack-detection/data/ctu_13/csv_sum_test/datactu_13pkl_sum025s_16-2pk1_test_df.csv", header=TRUE, sep=",")
resRS <- robpca(test_df, k=10, skew=TRUE,ndir=5000)
write(resRS$flag.all, file = "robpca_k19_datactu_13pkl_sum025s_16-2pk1_test_df", sep = "\n")

test_df <- read.csv("/home/thiago/dev/anomaly-detection/network-attack-detection/data/ctu_13/csv_sum_test/datactu_13pkl_sum015s_16-3pk1_test_df.csv", header=TRUE, sep=",")
resRS <- robpca(test_df, k=10, skew=TRUE,ndir=5000)
write(resRS$flag.all, file = "robpca_k19_datactu_13pkl_sum015s_16-3pk1_test_df", sep = "\n")
test_df <- read.csv("/home/thiago/dev/anomaly-detection/network-attack-detection/data/ctu_13/csv_sum_test/datactu_13pkl_sum025s_16-3pk1_test_df.csv", header=TRUE, sep=",")
resRS <- robpca(test_df, k=10, skew=TRUE,ndir=5000)
write(resRS$flag.all, file = "robpca_k19_datactu_13pkl_sum025s_16-3pk1_test_df", sep = "\n")

test_df <- read.csv("/home/thiago/dev/anomaly-detection/network-attack-detection/data/ctu_13/csv_sum_test/datactu_13pkl_sum015s_16pk1_test_df.csv", header=TRUE, sep=",")
resRS <- robpca(test_df, k=10, skew=TRUE,ndir=5000)
write(resRS$flag.all, file = "robpca_k19_datactu_13pkl_sum015s_16pk1_test_df", sep = "\n")
test_df <- read.csv("/home/thiago/dev/anomaly-detection/network-attack-detection/data/ctu_13/csv_sum_test/datactu_13pkl_sum025s_16pk1_test_df.csv", header=TRUE, sep=",")
resRS <- robpca(test_df, k=10, skew=TRUE,ndir=5000)
write(resRS$flag.all, file = "robpca_k19_datactu_13pkl_sum025s_16pk1_test_df", sep = "\n")

test_df <- read.csv("/home/thiago/dev/anomaly-detection/network-attack-detection/data/ctu_13/csv_sum_test/datactu_13pkl_sum015s_17pk1_test_df.csv", header=TRUE, sep=",")
resRS <- robpca(test_df, k=10, skew=TRUE,ndir=5000)
write(resRS$flag.all, file = "robpca_k19_datactu_13pkl_sum015s_17pk1_test_df", sep = "\n")
test_df <- read.csv("/home/thiago/dev/anomaly-detection/network-attack-detection/data/ctu_13/csv_sum_test/datactu_13pkl_sum025s_17pk1_test_df.csv", header=TRUE, sep=",")
resRS <- robpca(test_df, k=10, skew=TRUE,ndir=5000)
write(resRS$flag.all, file = "robpca_k19_datactu_13pkl_sum025s_17pk1_test_df", sep = "\n")

test_df <- read.csv("/home/thiago/dev/anomaly-detection/network-attack-detection/data/ctu_13/csv_sum_test/datactu_13pkl_sum015s_18pk1_test_df.csv", header=TRUE, sep=",")
resRS <- robpca(test_df, k=10, skew=TRUE,ndir=5000)
write(resRS$flag.all, file = "robpca_k19_datactu_13pkl_sum015s_18pk1_test_df", sep = "\n")
test_df <- read.csv("/home/thiago/dev/anomaly-detection/network-attack-detection/data/ctu_13/csv_sum_test/datactu_13pkl_sum025s_18pk1_test_df.csv", header=TRUE, sep=",")
resRS <- robpca(test_df, k=10, skew=TRUE,ndir=5000)
write(resRS$flag.all, file = "robpca_k19_datactu_13pkl_sum025s_18pk1_test_df", sep = "\n")

test_df <- read.csv("/home/thiago/dev/anomaly-detection/network-attack-detection/data/ctu_13/csv_sum_test/datactu_13pkl_sum015s_19pk1_test_df.csv", header=TRUE, sep=",")
resRS <- robpca(test_df, k=10, skew=TRUE,ndir=5000)
write(resRS$flag.all, file = "robpca_k19_datactu_13pkl_sum015s_19pk1_test_df", sep = "\n")
test_df <- read.csv("/home/thiago/dev/anomaly-detection/network-attack-detection/data/ctu_13/csv_sum_test/datactu_13pkl_sum025s_19pk1_test_df.csv", header=TRUE, sep=",")
resRS <- robpca(test_df, k=10, skew=TRUE,ndir=5000)
write(resRS$flag.all, file = "robpca_k19_datactu_13pkl_sum025s_19pk1_test_df", sep = "\n")

test_df <- read.csv("/home/thiago/dev/anomaly-detection/network-attack-detection/data/ctu_13/csv_sum_test/datactu_13pkl_sum015s_18-2pk1_test_df.csv", header=TRUE, sep=",")
resRS <- robpca(test_df, k=10, skew=TRUE,ndir=5000)
write(resRS$flag.all, file = "robpca_k19_datactu_13pkl_sum015s_18-2pk1_test_df", sep = "\n")
test_df <- read.csv("/home/thiago/dev/anomaly-detection/network-attack-detection/data/ctu_13/csv_sum_test/datactu_13pkl_sum025s_18-2pk1_test_df.csv", header=TRUE, sep=",")
resRS <- robpca(test_df, k=10, skew=TRUE,ndir=5000)
write(resRS$flag.all, file = "robpca_k19_datactu_13pkl_sum025s_18-2pk1_test_df", sep = "\n")