library(rospca)

test_df <- read.csv("/home/thiago/dev/anomaly-detection/network-attack-detection/data/ctu_13/agg_test_csv/15s_10.pk1_test_df.csv", header=TRUE, sep=",")
resRS <- robpca(test_df, k=2, skew=TRUE,ndir=5000)
write(resRS$flag.all, file = "robpca_k2_datactu_13pkl_sum015s_10pk1_test_df", sep = "\n")
test_df <- read.csv("/home/thiago/dev/anomaly-detection/network-attack-detection/data/ctu_13/agg_test_csv/25s_10.pk1_test_df.csv", header=TRUE, sep=",")
resRS <- robpca(test_df, k=2, skew=TRUE,ndir=5000)
write(resRS$flag.all, file = "robpca_k2_datactu_13pkl_sum025s_10pk1_test_df", sep = "\n")

test_df <- read.csv("/home/thiago/dev/anomaly-detection/network-attack-detection/data/ctu_13/agg_test_csv/15s_11.pk1_test_df.csv", header=TRUE, sep=",")
resRS <- robpca(test_df, k=2, skew=TRUE,ndir=5000)
write(resRS$flag.all, file = "robpca_k2_datactu_13pkl_sum015s_11pk1_test_df", sep = "\n")
test_df <- read.csv("/home/thiago/dev/anomaly-detection/network-attack-detection/data/ctu_13/agg_test_csv/25s_11.pk1_test_df.csv", header=TRUE, sep=",")
resRS <- robpca(test_df, k=2, skew=TRUE,ndir=5000)
write(resRS$flag.all, file = "robpca_k2_datactu_13pkl_sum025s_11pk1_test_df", sep = "\n")

test_df <- read.csv("/home/thiago/dev/anomaly-detection/network-attack-detection/data/ctu_13/agg_test_csv/15s_12.pk1_test_df.csv", header=TRUE, sep=",")
resRS <- robpca(test_df, k=2, skew=TRUE,ndir=5000)
write(resRS$flag.all, file = "robpca_k2_datactu_13pkl_sum015s_12pk1_test_df", sep = "\n")
test_df <- read.csv("/home/thiago/dev/anomaly-detection/network-attack-detection/data/ctu_13/agg_test_csv/25s_12.pk1_test_df.csv", header=TRUE, sep=",")
resRS <- robpca(test_df, k=2, skew=TRUE,ndir=5000)
write(resRS$flag.all, file = "robpca_k2_datactu_13pkl_sum025s_12pk1_test_df", sep = "\n")

test_df <- read.csv("/home/thiago/dev/anomaly-detection/network-attack-detection/data/ctu_13/agg_test_csv/15s_15-2.pk1_test_df.csv", header=TRUE, sep=",")
resRS <- robpca(test_df, k=2, skew=TRUE,ndir=5000)
write(resRS$flag.all, file = "robpca_k2_datactu_13pkl_sum015s_15-2pk1_test_df", sep = "\n")
test_df <- read.csv("/home/thiago/dev/anomaly-detection/network-attack-detection/data/ctu_13/agg_test_csv/25s_15-2.pk1_test_df.csv", header=TRUE, sep=",")
resRS <- robpca(test_df, k=2, skew=TRUE,ndir=5000)
write(resRS$flag.all, file = "robpca_k2_datactu_13pkl_sum025s_15-2pk1_test_df", sep = "\n")

test_df <- read.csv("/home/thiago/dev/anomaly-detection/network-attack-detection/data/ctu_13/agg_test_csv/15s_15-3.pk1_test_df.csv", header=TRUE, sep=",")
resRS <- robpca(test_df, k=2, skew=TRUE,ndir=5000)
write(resRS$flag.all, file = "robpca_k2_datactu_13pkl_sum015s_15-3pk1_test_df", sep = "\n")
test_df <- read.csv("/home/thiago/dev/anomaly-detection/network-attack-detection/data/ctu_13/agg_test_csv/25s_15-3.pk1_test_df.csv", header=TRUE, sep=",")
resRS <- robpca(test_df, k=2, skew=TRUE,ndir=5000)
write(resRS$flag.all, file = "robpca_k2_datactu_13pkl_sum025s_15-3pk1_test_df", sep = "\n")

test_df <- read.csv("/home/thiago/dev/anomaly-detection/network-attack-detection/data/ctu_13/agg_test_csv/15s_15.pk1_test_df.csv", header=TRUE, sep=",")
resRS <- robpca(test_df, k=2, skew=TRUE,ndir=5000)
write(resRS$flag.all, file = "robpca_k2_datactu_13pkl_sum015s_15pk1_test_df", sep = "\n")
test_df <- read.csv("/home/thiago/dev/anomaly-detection/network-attack-detection/data/ctu_13/agg_test_csv/25s_15.pk1_test_df.csv", header=TRUE, sep=",")
resRS <- robpca(test_df, k=2, skew=TRUE,ndir=5000)
write(resRS$flag.all, file = "robpca_k2_datactu_13pkl_sum025s_15pk1_test_df", sep = "\n")

test_df <- read.csv("/home/thiago/dev/anomaly-detection/network-attack-detection/data/ctu_13/agg_test_csv/15s_16-2.pk1_test_df.csv", header=TRUE, sep=",")
resRS <- robpca(test_df, k=2, skew=TRUE,ndir=5000)
write(resRS$flag.all, file = "robpca_k2_datactu_13pkl_sum015s_16-2pk1_test_df", sep = "\n")
test_df <- read.csv("/home/thiago/dev/anomaly-detection/network-attack-detection/data/ctu_13/agg_test_csv/25s_16-2.pk1_test_df.csv", header=TRUE, sep=",")
resRS <- robpca(test_df, k=2, skew=TRUE,ndir=5000)
write(resRS$flag.all, file = "robpca_k2_datactu_13pkl_sum025s_16-2pk1_test_df", sep = "\n")

test_df <- read.csv("/home/thiago/dev/anomaly-detection/network-attack-detection/data/ctu_13/agg_test_csv/15s_16-3.pk1_test_df.csv", header=TRUE, sep=",")
resRS <- robpca(test_df, k=2, skew=TRUE,ndir=5000)
write(resRS$flag.all, file = "robpca_k2_datactu_13pkl_sum015s_16-3pk1_test_df", sep = "\n")
test_df <- read.csv("/home/thiago/dev/anomaly-detection/network-attack-detection/data/ctu_13/agg_test_csv/25s_16-3.pk1_test_df.csv", header=TRUE, sep=",")
resRS <- robpca(test_df, k=2, skew=TRUE,ndir=5000)
write(resRS$flag.all, file = "robpca_k2_datactu_13pkl_sum025s_16-3pk1_test_df", sep = "\n")

test_df <- read.csv("/home/thiago/dev/anomaly-detection/network-attack-detection/data/ctu_13/agg_test_csv/15s_16.pk1_test_df.csv", header=TRUE, sep=",")
resRS <- robpca(test_df, k=2, skew=TRUE,ndir=5000)
write(resRS$flag.all, file = "robpca_k2_datactu_13pkl_sum015s_16pk1_test_df", sep = "\n")
test_df <- read.csv("/home/thiago/dev/anomaly-detection/network-attack-detection/data/ctu_13/agg_test_csv/25s_16.pk1_test_df.csv", header=TRUE, sep=",")
resRS <- robpca(test_df, k=2, skew=TRUE,ndir=5000)
write(resRS$flag.all, file = "robpca_k2_datactu_13pkl_sum025s_16pk1_test_df", sep = "\n")

test_df <- read.csv("/home/thiago/dev/anomaly-detection/network-attack-detection/data/ctu_13/agg_test_csv/15s_17.pk1_test_df.csv", header=TRUE, sep=",")
resRS <- robpca(test_df, k=2, skew=TRUE,ndir=5000)
write(resRS$flag.all, file = "robpca_k2_datactu_13pkl_sum015s_17pk1_test_df", sep = "\n")
test_df <- read.csv("/home/thiago/dev/anomaly-detection/network-attack-detection/data/ctu_13/agg_test_csv/25s_17.pk1_test_df.csv", header=TRUE, sep=",")
resRS <- robpca(test_df, k=2, skew=TRUE,ndir=5000)
write(resRS$flag.all, file = "robpca_k2_datactu_13pkl_sum025s_17pk1_test_df", sep = "\n")

test_df <- read.csv("/home/thiago/dev/anomaly-detection/network-attack-detection/data/ctu_13/agg_test_csv/15s_18.pk1_test_df.csv", header=TRUE, sep=",")
resRS <- robpca(test_df, k=2, skew=TRUE,ndir=5000)
write(resRS$flag.all, file = "robpca_k2_datactu_13pkl_sum015s_18pk1_test_df", sep = "\n")
test_df <- read.csv("/home/thiago/dev/anomaly-detection/network-attack-detection/data/ctu_13/agg_test_csv/25s_18.pk1_test_df.csv", header=TRUE, sep=",")
resRS <- robpca(test_df, k=2, skew=TRUE,ndir=5000)
write(resRS$flag.all, file = "robpca_k2_datactu_13pkl_sum025s_18pk1_test_df", sep = "\n")

test_df <- read.csv("/home/thiago/dev/anomaly-detection/network-attack-detection/data/ctu_13/agg_test_csv/15s_19.pk1_test_df.csv", header=TRUE, sep=",")
resRS <- robpca(test_df, k=2, skew=TRUE,ndir=5000)
write(resRS$flag.all, file = "robpca_k2_datactu_13pkl_sum015s_19pk1_test_df", sep = "\n")
test_df <- read.csv("/home/thiago/dev/anomaly-detection/network-attack-detection/data/ctu_13/agg_test_csv/25s_19.pk1_test_df.csv", header=TRUE, sep=",")
resRS <- robpca(test_df, k=2, skew=TRUE,ndir=5000)
write(resRS$flag.all, file = "robpca_k2_datactu_13pkl_sum025s_19pk1_test_df", sep = "\n")

test_df <- read.csv("/home/thiago/dev/anomaly-detection/network-attack-detection/data/ctu_13/agg_test_csv/15s_18-2.pk1_test_df.csv", header=TRUE, sep=",")
resRS <- robpca(test_df, k=2, skew=TRUE,ndir=5000)
write(resRS$flag.all, file = "robpca_k2_datactu_13pkl_sum015s_18-2pk1_test_df", sep = "\n")
test_df <- read.csv("/home/thiago/dev/anomaly-detection/network-attack-detection/data/ctu_13/agg_test_csv/25s_18-2.pk1_test_df.csv", header=TRUE, sep=",")
resRS <- robpca(test_df, k=2, skew=TRUE,ndir=5000)
write(resRS$flag.all, file = "robpca_k2_datactu_13pkl_sum025s_18-2pk1_test_df", sep = "\n")